### ISSUE TITLE
k0kubun/pp failure

### ISSUE THREAD

**Issue by mulev** [motemen/gore#51] opened 2015-09-14 20:03 UTC
Hello!

I've noticed a problem with pretty printer - some things causes failure of k0kubun/pp:
<pre>
➜  gore
gore version 0.2.5  :help for help
gore> :import "fmt"
gore> :import "github.com/moovweb/gokogiri/xml"
gore> doc := xml.CreateEmptyDocument([]byte("utf-8"), []byte("utf-8"))
...
gore> root := doc.Root()
<?xml version="1.0" encoding="utf-8"?>
<request/>

unexpected fault address 0xffffffffffffffff
fatal error: fault
[signal 0xb code=0x1 addr=0xffffffffffffffff pc=0x40ada08]
</pre>
Here is the details: https://gist.github.com/mulev/01eae0a8e0a7cd6d917f

**Comment by syohex** [comment] 2015-09-16 02:37
This is `k0kubun/pp` issue, not gore. `k0kubun/pp` crashes when cgo data structure has pointer fields which points invalid address(may be uninitialized). I suppose `gokogiri/xml` data structure has such fields. However this is not problem if such fields are not used. And it is difficult to fix this issue, because we cannot know whether address is valid.

We can reproduce this issue by following code.

```go
package main

/*
struct bar {
	int a;
};

struct foo {
	struct bar *ptr;
};

static void test(struct foo *f)
{
	f->ptr = (struct bar*)-1;
}
*/
import "C"
import "github.com/k0kubun/pp"
import "unsafe"

func main() {
	var tmp C.struct_foo

	C.test((*C.struct_foo)(unsafe.Pointer(&tmp)))
	pp.Print(tmp)
}
```

I got following result.

```
% go run test.go
unexpected fault address 0xffffffffffffffff
fatal error: fault
[signal 0xb code=0x1 addr=0xffffffffffffffff pc=0x4855c2]

goroutine 1 [running]:
runtime.throw(0x55f660, 0x5)
	/opt/go/src/runtime/panic.go:527 +0x90 fp=0xc8200ab118 sp=0xc8200ab100
runtime.sigpanic()
	/opt/go/src/runtime/sigpanic_unix.go:27 +0x2ab fp=0xc8200ab168 sp=0xc8200ab118
reflect.Value.Int(0x5037a0, 0xffffffffffffffff, 0xe5, 0x81e660)
	/opt/go/src/reflect/value.go:880 +0xc2 fp=0xc8200ab188 sp=0xc8200ab168
github.com/k0kubun/pp.(*printer).raw(0xc820014680, 0x0, 0x0)
	/home/syohei/go/src/github.com/k0kubun/pp/printer.go:347 +0x1fe fp=0xc8200ab248 sp=0xc8200ab188
github.com/k0kubun/pp.(*printer).String(0xc820014680, 0x0, 0x0)
	/home/syohei/go/src/github.com/k0kubun/pp/printer.go:57 +0x216 fp=0xc8200ab368 sp=0xc8200ab248
github.com/k0kubun/pp.(*printer).format(0xc820014440, 0x55cf40, 0xc82000e820, 0x0, 0x0)
	/home/syohei/go/src/github.com/k0kubun/pp/printer.go:378 +0x11c fp=0xc8200ab3d0 sp=0xc8200ab368
github.com/k0kubun/pp.(*printer).printStruct.func1()
	/home/syohei/go/src/github.com/k0kubun/pp/printer.go:185 +0x247 fp=0xc8200ab580 sp=0xc8200ab3d0
github.com/k0kubun/pp.(*printer).indented(0xc820014440, 0xc8200ab5e0)
	/home/syohei/go/src/github.com/k0kubun/pp/printer.go:337 +0x29 fp=0xc8200ab588 sp=0xc8200ab580
github.com/k0kubun/pp.(*printer).printStruct(0xc820014440)
	/home/syohei/go/src/github.com/k0kubun/pp/printer.go:187 +0x234 fp=0xc8200ab618 sp=0xc8200ab588
github.com/k0kubun/pp.(*printer).String(0xc820014440, 0x0, 0x0)
	/home/syohei/go/src/github.com/k0kubun/pp/printer.go:65 +0x729 fp=0xc8200ab738 sp=0xc8200ab618
github.com/k0kubun/pp.(*printer).format(0xc820014400, 0x55cf40, 0xc82000e5c0, 0x0, 0x0)
	/home/syohei/go/src/github.com/k0kubun/pp/printer.go:378 +0x11c fp=0xc8200ab7a0 sp=0xc8200ab738
github.com/k0kubun/pp.(*printer).printPtr(0xc820014400)
	/home/syohei/go/src/github.com/k0kubun/pp/printer.go:290 +0x376 fp=0xc8200ab890 sp=0xc8200ab7a0
github.com/k0kubun/pp.(*printer).String(0xc820014400, 0x0, 0x0)
	/home/syohei/go/src/github.com/k0kubun/pp/printer.go:73 +0x6ed fp=0xc8200ab9b0 sp=0xc8200ab890
github.com/k0kubun/pp.(*printer).format(0xc820014180, 0x55cf40, 0xc82000e580, 0x0, 0x0)
	/home/syohei/go/src/github.com/k0kubun/pp/printer.go:378 +0x11c fp=0xc8200aba18 sp=0xc8200ab9b0
github.com/k0kubun/pp.(*printer).printStruct.func1()
	/home/syohei/go/src/github.com/k0kubun/pp/printer.go:185 +0x247 fp=0xc8200abbc8 sp=0xc8200aba18
github.com/k0kubun/pp.(*printer).indented(0xc820014180, 0xc8200abc28)
	/home/syohei/go/src/github.com/k0kubun/pp/printer.go:337 +0x29 fp=0xc8200abbd0 sp=0xc8200abbc8
github.com/k0kubun/pp.(*printer).printStruct(0xc820014180)
	/home/syohei/go/src/github.com/k0kubun/pp/printer.go:187 +0x234 fp=0xc8200abc60 sp=0xc8200abbd0
github.com/k0kubun/pp.(*printer).String(0xc820014180, 0x0, 0x0)
	/home/syohei/go/src/github.com/k0kubun/pp/printer.go:65 +0x729 fp=0xc8200abd80 sp=0xc8200abc60
github.com/k0kubun/pp.format(0x5325c0, 0xffffffffffffffff, 0x0, 0x0)
	/home/syohei/go/src/github.com/k0kubun/pp/printer.go:25 +0x45 fp=0xc8200abda0 sp=0xc8200abd80
github.com/k0kubun/pp.formatAll(0xc8200abf10, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/syohei/go/src/github.com/k0kubun/pp/pp.go:135 +0xfd fp=0xc8200abe60 sp=0xc8200abda0
github.com/k0kubun/pp.Print(0xc8200abf10, 0x1, 0x1, 0x404297, 0x0, 0x0)
	/home/syohei/go/src/github.com/k0kubun/pp/pp.go:29 +0x4d fp=0xc8200abec0 sp=0xc8200abe60
main.main()
	/home/syohei/junk/go/pp/test.go:25 +0xb3 fp=0xc8200abf40 sp=0xc8200abec0
runtime.main()
	/opt/go/src/runtime/proc.go:111 +0x2b0 fp=0xc8200abf90 sp=0xc8200abf40
runtime.goexit()
	/opt/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200abf98 sp=0xc8200abf90

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/opt/go/src/runtime/asm_amd64.s:1696 +0x1
exit status 2
```

**Comment by motemen** [comment] 2015-12-11 05:11
@syohex thank you! Closing this issue.

**Closed by motemen** 2015-12-11 05:11 UTC
