### ISSUE TITLE
In `t = time.Now()` expression `t` will change its value each time you print it

### ISSUE THREAD

**Issue by dengshuan** [motemen/gore#58] opened 2015-12-09 12:23 UTC
When asign `time.Now()` to a variable, that variable is not fixed and changes every time you print it

``` go
t1 := time.Now()
t2 := time.Now()
t1 // one value
t1 // would print another value
t2.Sub(t1)
t2.Sub(t1) // different from previous evaluation
```

my gore version is 0.2.5 and go version is 1.5.2

**Comment by motemen** [comment] 2015-12-11 05:10
Unfortunately this is [an expected behavior of gore](https://github.com/motemen/gore#faqcaveats), which invokes `go run` on each REPL input. You cannot expect the same values to be printed if the code involves I/O.

I'd love to hear any idea to solve this problem, thanks.

**Comment by HALtheWise** [comment] 2016-01-07 04:44
To fix this, gore could substitute its own wrappers for certain standard library packages that store the output in a database and regurgitate it rather than executing again. This would also fix the counterintuitive behavior caused by typing multiple fmt.Println(...) calls in one repl shell. I'm not sure how to properly extend this behavior beyond the standard library, as detecting and recording the side-effects of unknown functions is hard.

**Comment by itchyny** [comment] 2020-01-20 10:47
This is a core issue of gore but closing as duplicate of #67.

**Closed by itchyny** 2020-01-20 10:47 UTC
Labels: interpreter
